### ISSUE TITLE
Is this finished?

### ISSUE THREAD

**Issue by christianbundy** [lsd/ero#1]
Sorry if this is a dumb question, I just can't tell if it works, or how to use your API. Thanks!

**Comment by lsd** [comment]
Hey, sorry it's far from finished. I've been busy with work and the mrs. Thanks for bringing this up to my attention again, I'm going to see where I left off and get going on it. What feature(s)/applications did you have in mind? I can prioritize the relevant parts of the API first.

**Comment by christianbundy** [comment]
None yet, just interested in modernizing Erowid and wanted to see what you were up to! :+1:

**Comment by lsd** [comment]
Work on this was halted due to the trending popularity of Javascript vs .. everything else. This will be ported to Javascript (ES5,6+) as an npm package and standalone node script for convenience. Afterwards I will write a Ruby and possibly a Python wrapper around the Javascript code to ensure this project has a wider reach. Thanks for being patient.
